### ISSUE TITLE
Android crash when leave sessionActiivty

### ISSUE THREAD

**Issue by quququququ** [OpenVidu/openvidu-tutorials#126]
[MALI] GLES error info: <texture> was previously created with a target that doesn't match that of <target>
E/org.webrtc.Logging: EglRenderer: Exception on EglRenderer thread
    EglRenderer: java.lang.RuntimeException: glUseProgram: GLES20 error: 1282
E/org.webrtc.Logging: EglRenderer: java.lang.RuntimeException: glUseProgram: GLES20 error: 1282
        at org.webrtc.GlUtil.checkNoGLES2Error(GlUtil.java:37)
        at org.webrtc.GlShader.useProgram(GlShader.java:118)
        at org.webrtc.GlGenericDrawer.prepareShader(GlGenericDrawer.java:246)
        at org.webrtc.GlGenericDrawer.drawOes(GlGenericDrawer.java:159)
        at org.webrtc.GlRectDrawer.drawOes(GlRectDrawer.java:14)
        at org.webrtc.VideoFrameDrawer.drawTexture(VideoFrameDrawer.java:40)
        at org.webrtc.VideoFrameDrawer.drawFrame(VideoFrameDrawer.java:213)
        at org.webrtc.EglRenderer.renderFrameOnRenderThread(EglRenderer.java:662)
        at org.webrtc.EglRenderer.lambda$vWDJEj1GWjHSjwoQQjEEK_IVOJE(Unknown Source:0)
        at org.webrtc.-$$Lambda$EglRenderer$vWDJEj1GWjHSjwoQQjEEK_IVOJE.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/AndroidRuntime: FATAL EXCEPTION: local_gl_surface_viewEglRenderer
    Process: io.openvidu.openvidu_android, PID: 15935
    java.lang.RuntimeException: glUseProgram: GLES20 error: 1282
        at org.webrtc.GlUtil.checkNoGLES2Error(GlUtil.java:37)
        at org.webrtc.GlShader.useProgram(GlShader.java:118)
        at org.webrtc.GlGenericDrawer.prepareShader(GlGenericDrawer.java:246)
        at org.webrtc.GlGenericDrawer.drawOes(GlGenericDrawer.java:159)
        at org.webrtc.GlRectDrawer.drawOes(GlRectDrawer.java:14)
        at org.webrtc.VideoFrameDrawer.drawTexture(VideoFrameDrawer.java:40)
        at org.webrtc.VideoFrameDrawer.drawFrame(VideoFrameDrawer.java:213)
        at org.webrtc.EglRenderer.renderFrameOnRenderThread(EglRenderer.java:662)
        at org.webrtc.EglRenderer.lambda$vWDJEj1GWjHSjwoQQjEEK_IVOJE(Unknown Source:0)
        at org.webrtc.-$$Lambda$EglRenderer$vWDJEj1GWjHSjwoQQjEEK_IVOJE.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by CSantosM** [comment]
Fixed on commit a3ee7df193b992bd617a05bca6449ddef7d3cf0c
