### ISSUE TITLE
Native-Android app not streaming video in Web (Basic Conferencing)

### ISSUE THREAD

**Issue by amit2319** [OpenVidu/openvidu-tutorials#74]
Native Android demo connects with the Basic Conferencing Web App Session but not able to stream the Video (Participant name is displayed but the video doesn't i.e. white screen in the video box), whereas video from Web App is received at the Android end properly.

**Comment by skydeveloper9** [comment]
When will this bug be fixed?
And what's the problem?

**Comment by micaelgallego** [comment]
We don't know what is the problem.

Please follow carefully the steps of this tutorial 

https://docs.openvidu.io/en/2.12.0/tutorials/openvidu-android/

and share with us logs of all parts (openvidu server, android app, etc)

**Comment by skydeveloper9** [comment]
i try
server version =  2.12
android master branch 
result : not working


server version =  2.12
and checkout android version to tag v2.12.0
result : not working

downgrade server to 2.11  
android master branch 
result : not working

downgrade server to 2.11  
and checkout android version to tag v2.12.0
result : it's work

i think  last commit for android not compatible with last server version
(rpc json is not compatible with last version)

**Comment by micaelgallego** [comment]
Thank you for detailed information.

@CSantosM, can you take a look?

**Comment by skydeveloper9** [comment]
this is server log

`org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantPublished","params":{"id":"con_FPFvHC4bwN","streams"
:[{"id":"str_CAM_Zv8e_con_FPFvHC4bwN","createdAt":1586261469311,"hasAudio":true,"hasVideo":true,"audioActive":true,"videoActive":true,"typeOfVideo":"CAMERA
","frameRate":30,"videoDimensions":"{\"width\":320, \"height\":240}","filter":{}}]},"jsonrpc":"2.0"}' to websocket with native sessionId '20fee3e7-d203-f39
6-d283-8da3c47e706e'
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:123)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:49)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:74)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
        at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
        at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:105)
        at io.openvidu.server.core.SessionEventsHandler.onPublishMedia(SessionEventsHandler.java:233)
        at io.openvidu.server.kurento.core.KurentoSessionManager.publishVideo(KurentoSessionManager.java:354)
        at io.openvidu.server.rpc.RpcHandler.publishVideo(RpcHandler.java:323)
        at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:124)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:142)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [2] has been closed and no method (apart from close()) may be called on a closed session
        at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:836)
        at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:433)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215)
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:119)
        ... 15 common frames omitted`

**Comment by CSantosM** [comment]
I've just tested openvidu-android with openvidu-call (2.14.0) and openvidu-insecure-js (2.14.0) locally and pointing to demos.openvidu.io (2.14.0) and the participants are able to see each other.
